export const noPayload = {
  // defaultMixins,mixins,mapStateToVariables
  '[],[],*': {
  },
  '[],pageViewPayloadMixins,': {
    prop11: 'prop11 from topPageProps',
    prop30: 'prop30 from globalProps',
    prop31: 'prop31 from globalProps',
    prop41: 'prop41 from topPageProps',
  },
  '[],pageViewPayloadMixins,mapStateToVariables': {
    prop11: 'prop11 from topPageProps',
    prop30: 'prop30 from globalProps',
    prop31: 'prop31 from globalProps',
    prop41: 'prop41 from topPageProps',
    prop51: 'language from article',
  },
  '*,false,*': {
  },
  '*,true,': {
    prop10: 'prop10 from topPageProps',
    prop11: 'prop11 from topPageProps',
    prop15: 'prop15 from topPageProps',
    prop30: 'prop30 from globalProps',
    prop31: 'prop31 from globalProps',
    prop40: 'prop40 from topPageProps',
    prop41: 'prop41 from topPageProps',
  },
  'pageViewMixins,[],': {
    prop10: 'prop10 from topPageProps',
    prop30: 'prop30 from globalProps',
    prop40: 'prop40 from topPageProps',
  },
  'pageViewMixins,[],mapStateToVariables': {
    prop10: 'prop10 from topPageProps',
    prop30: 'prop30 from globalProps',
    prop40: 'prop40 from topPageProps',
    prop50: 'category from article',
  },
  'pageViewMixins,pageViewPayloadMixins,': {
    prop10: 'prop10 from topPageProps',
    prop11: 'prop11 from topPageProps',
    prop30: 'prop30 from globalProps',
    prop31: 'prop31 from globalProps',
    prop40: 'prop40 from topPageProps',
    prop41: 'prop41 from topPageProps',
  },
  'pageViewMixins,pageViewPayloadMixins,mapStateToVariables': {
    prop10: 'prop10 from topPageProps',
    prop11: 'prop11 from topPageProps',
    prop30: 'prop30 from globalProps',
    prop31: 'prop31 from globalProps',
    prop40: 'prop40 from topPageProps',
    prop41: 'prop41 from topPageProps',
    prop50: 'category from article',
    prop51: 'language from article',
  },
  '*,true,mapStateToVariables': {
    prop10: 'prop10 from topPageProps',
    prop11: 'prop11 from topPageProps',
    prop15: 'prop15 from topPageProps',
    prop30: 'prop30 from globalProps',
    prop31: 'prop31 from globalProps',
    prop40: 'prop40 from topPageProps',
    prop41: 'prop41 from topPageProps',
    prop50: 'category from article',
    prop51: 'language from article',
    prop60: 'links from article',
  },
  '[],eventPayloadMixins,': {
    prop10: 'prop10 from topPageProps',
    prop31: 'prop31 from globalProps',
  },
  '[],eventPayloadMixins,mapStateToVariables': {
    prop10: 'prop10 from topPageProps',
    prop31: 'prop31 from globalProps',
    prop50: 'category from article',
    prop60: 'links from article',
  },
  'eventMixins,[],': {
    prop15: 'prop15 from topPageProps',
    prop31: 'prop31 from globalProps',
    prop41: 'prop41 from topPageProps',
  },
  'eventMixins,[],mapStateToVariables': {
    prop15: 'prop15 from topPageProps',
    prop31: 'prop31 from globalProps',
    prop41: 'prop41 from topPageProps',
    prop51: 'language from article',
  },
  'eventMixins,eventPayloadMixins,': {
    prop10: 'prop10 from topPageProps',
    prop15: 'prop15 from topPageProps',
    prop31: 'prop31 from globalProps',
    prop41: 'prop41 from topPageProps',
  },
  'eventMixins,eventPayloadMixins,mapStateToVariables': {
    prop10: 'prop10 from topPageProps',
    prop15: 'prop15 from topPageProps',
    prop31: 'prop31 from globalProps',
    prop41: 'prop41 from topPageProps',
    prop50: 'category from article',
    prop51: 'language from article',
    prop60: 'links from article',
  },
}

export const withPageViewPayload = {
  '[],[],*': {
    pageName: 'top',
    prop10: 'prop10 from pageView payload',
  },
  '[],pageViewPayloadMixins,': {
    prop11: 'prop11 from topPageProps',
    prop30: 'prop30 from globalProps',
    prop31: 'prop31 from globalProps',
    prop41: 'prop41 from topPageProps',
    pageName: 'top',
    prop10: 'prop10 from pageView payload',
  },
  '[],pageViewPayloadMixins,mapStateToVariables': {
    prop11: 'prop11 from topPageProps',
    prop30: 'prop30 from globalProps',
    prop31: 'prop31 from globalProps',
    prop41: 'prop41 from topPageProps',
    prop51: 'language from article',
    pageName: 'top',
    prop10: 'prop10 from pageView payload',
  },
  '*,false,*': {
    pageName: 'top',
    prop10: 'prop10 from pageView payload',
  },
  '*,true,': {
    // prop10: 'prop10 from topPageProps',
    prop11: 'prop11 from topPageProps',
    prop15: 'prop15 from topPageProps',
    prop30: 'prop30 from globalProps',
    prop31: 'prop31 from globalProps',
    prop40: 'prop40 from topPageProps',
    prop41: 'prop41 from topPageProps',
    pageName: 'top',
    prop10: 'prop10 from pageView payload',
  },
  'pageViewMixins,[],': {
    // prop10: 'prop10 from topPageProps',
    prop30: 'prop30 from globalProps',
    prop40: 'prop40 from topPageProps',
    pageName: 'top',
    prop10: 'prop10 from pageView payload',
  },
  'pageViewMixins,[],mapStateToVariables': {
    // prop10: 'prop10 from topPageProps',
    prop30: 'prop30 from globalProps',
    prop40: 'prop40 from topPageProps',
    prop50: 'category from article',
    pageName: 'top',
    prop10: 'prop10 from pageView payload',
  },
  'pageViewMixins,pageViewPayloadMixins,': {
    // prop10: 'prop10 from topPageProps',
    prop11: 'prop11 from topPageProps',
    prop30: 'prop30 from globalProps',
    prop31: 'prop31 from globalProps',
    prop40: 'prop40 from topPageProps',
    prop41: 'prop41 from topPageProps',
    pageName: 'top',
    prop10: 'prop10 from pageView payload',
  },
  'pageViewMixins,pageViewPayloadMixins,mapStateToVariables': {
    // prop10: 'prop10 from topPageProps',
    prop11: 'prop11 from topPageProps',
    prop30: 'prop30 from globalProps',
    prop31: 'prop31 from globalProps',
    prop40: 'prop40 from topPageProps',
    prop41: 'prop41 from topPageProps',
    prop50: 'category from article',
    prop51: 'language from article',
    pageName: 'top',
    prop10: 'prop10 from pageView payload',
  },
  '*,true,mapStateToVariables': {
    // prop10: 'prop10 from topPageProps',
    prop11: 'prop11 from topPageProps',
    prop15: 'prop15 from topPageProps',
    prop30: 'prop30 from globalProps',
    prop31: 'prop31 from globalProps',
    prop40: 'prop40 from topPageProps',
    prop41: 'prop41 from topPageProps',
    prop50: 'category from article',
    prop51: 'language from article',
    prop60: 'links from article',
    pageName: 'top',
    prop10: 'prop10 from pageView payload',
  },
}

export const withEventPayload = {
  '[],[],*': {
    events: ['event1'],
    prop11: 'prop11 from event payload',
  },
  '[],eventPayloadMixins,': {
    prop10: 'prop10 from topPageProps',
    prop31: 'prop31 from globalProps',
    events: ['event1'],
    prop11: 'prop11 from event payload',
  },
  '[],eventPayloadMixins,mapStateToVariables': {
    prop10: 'prop10 from topPageProps',
    prop31: 'prop31 from globalProps',
    prop50: 'category from article',
    prop60: 'links from article',
    events: ['event1'],
    prop11: 'prop11 from event payload',
  },
  '*,false,*': {
    events: ['event1'],
    prop11: 'prop11 from event payload',
  },
  '*,true,': {
    prop10: 'prop10 from topPageProps',
    // prop11: 'prop11 from topPageProps',
    prop15: 'prop15 from topPageProps',
    prop30: 'prop30 from globalProps',
    prop31: 'prop31 from globalProps',
    prop40: 'prop40 from topPageProps',
    prop41: 'prop41 from topPageProps',
    events: ['event1'],
    prop11: 'prop11 from event payload',
  },
  'eventMixins,[],': {
    prop15: 'prop15 from topPageProps',
    prop31: 'prop31 from globalProps',
    prop41: 'prop41 from topPageProps',
    events: ['event1'],
    prop11: 'prop11 from event payload',
  },
  'eventMixins,[],mapStateToVariables': {
    prop15: 'prop15 from topPageProps',
    prop31: 'prop31 from globalProps',
    prop41: 'prop41 from topPageProps',
    prop51: 'language from article',
    events: ['event1'],
    prop11: 'prop11 from event payload',
  },
  'eventMixins,eventPayloadMixins,': {
    prop10: 'prop10 from topPageProps',
    prop15: 'prop15 from topPageProps',
    prop31: 'prop31 from globalProps',
    prop41: 'prop41 from topPageProps',
    events: ['event1'],
    prop11: 'prop11 from event payload',
  },
  'eventMixins,eventPayloadMixins,mapStateToVariables': {
    prop10: 'prop10 from topPageProps',
    prop15: 'prop15 from topPageProps',
    prop31: 'prop31 from globalProps',
    prop41: 'prop41 from topPageProps',
    prop50: 'category from article',
    prop51: 'language from article',
    prop60: 'links from article',
    events: ['event1'],
    prop11: 'prop11 from event payload',
  },
  '*,true,mapStateToVariables': {
    prop10: 'prop10 from topPageProps',
    // prop11: 'prop11 from topPageProps',
    prop15: 'prop15 from topPageProps',
    prop30: 'prop30 from globalProps',
    prop31: 'prop31 from globalProps',
    prop40: 'prop40 from topPageProps',
    prop41: 'prop41 from topPageProps',
    prop50: 'category from article',
    prop51: 'language from article',
    prop60: 'links from article',
    events: ['event1'],
    prop11: 'prop11 from event payload',
  },
}

export const withEventPayloadAfterPageView = {
  '[],[],*': {
    events: ['event1'],
    prop11: 'prop11 from event payload',
  },
  '[],eventPayloadMixins,': {
    // prop10: 'prop10 from topPageProps',
    prop31: 'prop31 from globalProps',
    events: ['event1'],
    prop11: 'prop11 from event payload',
    prop10: 'prop10 from pageView payload',
  },
  '[],eventPayloadMixins,mapStateToVariables': {
    // prop10: 'prop10 from topPageProps',
    prop31: 'prop31 from globalProps',
    prop50: 'category from article',
    prop60: 'links from article',
    events: ['event1'],
    prop11: 'prop11 from event payload',
    prop10: 'prop10 from pageView payload',
  },
  '*,false,*': {
    events: ['event1'],
    prop11: 'prop11 from event payload',
  },
  '*,true,': {
    // prop10: 'prop10 from topPageProps',
    // prop11: 'prop11 from topPageProps',
    prop15: 'prop15 from topPageProps',
    prop30: 'prop30 from globalProps',
    prop31: 'prop31 from globalProps',
    prop40: 'prop40 from topPageProps',
    prop41: 'prop41 from topPageProps',
    events: ['event1'],
    prop11: 'prop11 from event payload',
    pageName: 'top',
    prop10: 'prop10 from pageView payload',
  },
  'eventMixins,[],': {
    prop15: 'prop15 from topPageProps',
    prop31: 'prop31 from globalProps',
    prop41: 'prop41 from topPageProps',
    events: ['event1'],
    prop11: 'prop11 from event payload',
  },
  'eventMixins,[],mapStateToVariables': {
    prop15: 'prop15 from topPageProps',
    prop31: 'prop31 from globalProps',
    prop41: 'prop41 from topPageProps',
    prop51: 'language from article',
    events: ['event1'],
    prop11: 'prop11 from event payload',
  },
  'eventMixins,eventPayloadMixins,': {
    // prop10: 'prop10 from topPageProps',
    prop15: 'prop15 from topPageProps',
    prop31: 'prop31 from globalProps',
    prop41: 'prop41 from topPageProps',
    events: ['event1'],
    prop11: 'prop11 from event payload',
    prop10: 'prop10 from pageView payload',
  },
  'eventMixins,eventPayloadMixins,mapStateToVariables': {
    // prop10: 'prop10 from topPageProps',
    prop15: 'prop15 from topPageProps',
    prop31: 'prop31 from globalProps',
    prop41: 'prop41 from topPageProps',
    prop50: 'category from article',
    prop51: 'language from article',
    prop60: 'links from article',
    events: ['event1'],
    prop11: 'prop11 from event payload',
    prop10: 'prop10 from pageView payload',
  },
  '*,true,mapStateToVariables': {
    // prop10: 'prop10 from topPageProps',
    // prop11: 'prop11 from topPageProps',
    prop15: 'prop15 from topPageProps',
    prop30: 'prop30 from globalProps',
    prop31: 'prop31 from globalProps',
    prop40: 'prop40 from topPageProps',
    prop41: 'prop41 from topPageProps',
    prop50: 'category from article',
    prop51: 'language from article',
    prop60: 'links from article',
    events: ['event1'],
    prop11: 'prop11 from event payload',
    pageName: 'top',
    prop10: 'prop10 from pageView payload',
  },
}
